### ISSUE TITLE
ESP32-S3 compiling but not working

### ISSUE THREAD

**Issue by Alfred1975** [UncleRus/EvLamp#3]
Hello! 

I tried to run your project on ESP32-S3. Its compiling, working, button and wifi are ok but leds are not working. 

SImple RMT example is working from IDF v5 with the same leds and GPIO.

I see that you indicated that not all the ESP32 chips are compatible. S3 is also not compatible? 

But no errors in Serial monitor also..

Regards!

**Comment by UncleRus** [comment]
Hello!

Unfortunately, I don’t have ESP32-S3 on hand, but judging by what I read in the ESP-IDF documentation, evlamp should work with it.

Let's first check if the [default example for the led_strip driver from esp-idf-lib](https://github.com/UncleRus/esp-idf-lib/tree/master/examples/led_strip/default) works.

Build and flash an example, connect the LED matrix to the output (GPIO 5 by default) and check that the LEDs change colors.

**Comment by Alfred1975** [comment]
Hello! 

As I indicated in my first post the [default example for the led_strip driver from esp-idf-lib] is working. 

But nothing happen with leds when I flash your project. The same GPIO.

From wifi or button I change the aniation but nothing happen with leds...

**Comment by UncleRus** [comment]
Can I see the serial console output log?
Please press the hardware buttons (if there are any) or turn the lamp on/off from the web interface (big switch in the header).

**Comment by Alfred1975** [comment]
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2b (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DOUT, clock div:1
load:0x3fce3818,len:0x1750
load:0x403c9700,len:0x4
load:0x403c9704,len:0xc00
load:0x403cc700,len:0x2e04
entry 0x403c9908
I (27) boot: ESP-IDF v5.1.2 2nd stage bootloader
I (27) boot: compile time Nov 24 2023 19:08:04
I (27) boot: Multicore bootloader
I (30) boot: chip revision: v0.2
I (34) boot.esp32s3: Boot SPI Speed : 80MHz
I (39) boot.esp32s3: SPI Mode       : DOUT
I (43) boot.esp32s3: SPI Flash Size : 8MB
I (48) boot: Enabling RNG early entropy source...
I (54) boot: Partition Table:
I (57) boot: ## Label            Usage          Type ST Offset   Length
I (64) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (72) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (79) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  3 factory          factory app      00 00 00010000 00150000
I (94) boot:  4 ota_0            OTA app          00 10 00160000 00150000
I (102) boot:  5 ota_1            OTA app          00 11 002b0000 00150000
I (109) boot: End of partition table
I (114) boot: Defaulting to factory image
I (118) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=45d14h (285972) map
I (182) esp_image: segment 1: paddr=00055d3c vaddr=3fc97e00 size=0530ch ( 21260) load
I (187) esp_image: segment 2: paddr=0005b050 vaddr=40374000 size=04fc8h ( 20424) load
I (192) esp_image: segment 3: paddr=00060020 vaddr=42000020 size=9e9d8h (649688) map
I (321) esp_image: segment 4: paddr=000fea00 vaddr=40378fc8 size=0ed98h ( 60824) load
I (343) boot: Loaded app from partition at offset 0x10000
I (344) boot: Disabling RNG early entropy source...
I (355) cpu_start: Multicore app
I (355) cpu_start: Pro cpu up.
I (356) cpu_start: Starting app cpu, entry point is 0x4037555c
0x4037555c: call_start_cpu1 at C:/esp/esp-idf/components/esp_system/port/cpu_start.c:157

I (0) cpu_start: App cpu up.
I (374) cpu_start: Pro cpu start user code
I (374) cpu_start: cpu freq: 160000000 Hz
I (374) cpu_start: Application information:
I (377) cpu_start: Project name:     EvLamp
I (382) cpu_start: App version:      0.7.3
I (386) cpu_start: Compile time:     Nov 24 2023 19:07:27
I (392) cpu_start: ELF file SHA256:  48d1208000b0d2b3...
I (398) cpu_start: ESP-IDF:          v5.1.2
I (403) cpu_start: Min chip rev:     v0.0
I (408) cpu_start: Max chip rev:     v0.99 
I (413) cpu_start: Chip rev:         v0.2
I (418) heap_init: Initializing. RAM available for dynamic allocation:
I (425) heap_init: At 3FCA1570 len 000481A0 (288 KiB): DRAM
I (431) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (438) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (444) heap_init: At 600FE010 len 00001FD8 (7 KiB): RTCRAM
I (451) spi_flash: detected chip: gd
I (454) spi_flash: flash io: dout
W (459) rmt(legacy): legacy driver is deprecated, please migrate to `driver/rmt_tx.h` and/or `driver/rmt_rx.h`
I (469) sleep: Configure to isolate all GPIO pins in sleep state
I (476) sleep: Enable automatic switching of GPIO sleep configuration
I (483) app_start: Starting scheduler on CPU0
I (488) app_start: Starting scheduler on CPU1
I (488) main_task: Started on CPU0
I (498) main_task: Calling app_main()
I (502) EvLamp: Starting EvLamp
I (505) EvLamp: Free heap: 336416 bytes
I (587) EvLamp: Effect 0: 'Color lamp'
I (588) EvLamp:     Red: 255 (min 0, max 255, def 255)
I (589) EvLamp:     Green: 159 (min 0, max 255, def 159)
I (593) EvLamp:     Blue: 70 (min 0, max 255, def 70)
I (599) EvLamp: Effect 1: 'Fire'
I (603) EvLamp:     Palette: 2 (min 0, max 7, def 0)
I (608) EvLamp:     Scale: 60 (min 10, max 100, def 60)
I (614) EvLamp: Effect 2: 'Sparkles'
I (619) EvLamp:     Number of sparkles: 10 (min 1, max 50, def 10)
I (625) EvLamp:     Fadeout speed: 80 (min 10, max 150, def 80)
I (632) EvLamp: Effect 3: 'Lava'
I (636) EvLamp:     Scale: 40 (min 5, max 100, def 40)
I (642) EvLamp:     Speed: 15 (min 0, max 50, def 15)
I (648) EvLamp:     Mode: 1 (min 0, max 2, def 1)
I (653) EvLamp:     Palette: 0 (min 0, max 13, def 0)
I (658) EvLamp: Effect 4: 'Waterfall'
I (663) EvLamp:     Mode: 0 (min 0, max 2, def 0)
I (668) EvLamp:     Color: 160 (min 0, max 255, def 160)
I (674) EvLamp:     Cooling: 10 (min 5, max 100, def 10)
I (680) EvLamp:     Sparking: 60 (min 20, max 200, def 60)
I (686) EvLamp: Effect 5: 'Plasma waves'
I (691) EvLamp:     Speed: 40 (min 1, max 255, def 40)
I (697) EvLamp: Effect 6: 'DNA helix'
I (701) EvLamp:     Rotation speed: 50 (min 10, max 100, def 50)
I (708) EvLamp:     Spiral size: 5 (min 1, max 10, def 5)
I (714) EvLamp:     Add white border: 1 (min 0, max 1, def 1)
I (720) EvLamp: Effect 7: 'Matrix'
I (724) EvLamp:     Density: 150 (min 0, max 255, def 150)
I (730) EvLamp: Effect 8: 'Crazy bees'
I (735) EvLamp:     Number of bees: 3 (min 1, max 10, def 3)
I (741) EvLamp:     Bee hue: 100 (min 0, max 255, def 100)
I (748) EvLamp:     Bee saturation: 0 (min 0, max 255, def 0)
I (754) EvLamp: Effect 9: 'Rain'
I (758) EvLamp:     Colored: 0 (min 0, max 1, def 0)
I (764) EvLamp:     Hue: 128 (min 0, max 255, def 128)
I (769) EvLamp:     Density: 50 (min 0, max 100, def 50)
I (775) EvLamp:     Tail length: 150 (min 100, max 200, def 150)
I (782) EvLamp: Effect 10: 'Rainbow'
I (786) EvLamp:     Direction: 0 (min 0, max 2, def 0)
I (792) EvLamp:     Scale: 20 (min 1, max 50, def 20)
I (798) EvLamp:     Speed: 10 (min 1, max 40, def 5)
I (803) EvLamp: Effect 11: 'Rays'
I (807) EvLamp:     Speed: 10 (min 0, max 50, def 10)
I (813) EvLamp:     Min rays: 3 (min 1, max 10, def 3)
I (819) EvLamp:     Max rays: 6 (min 1, max 20, def 6)
I (825) EvLamp: Effect 12: 'Metaballs'
I (829) EvLamp:     Palette: 0 (min 0, max 2, def 0)
I (835) EvLamp:     Balls: 3 (min 2, max 6, def 3)
I (840) EvLamp: Effect 13: 'Water'
I (844) EvLamp:     Hue: 150 (min 0, max 255, def 150)
I (850) EvLamp:     Saturation: 255 (min 0, max 255, def 255)
I (857) EvLamp:     Speed: 30 (min 0, max 54, def 30)
I (862) EvLamp: Effect 14: 'Holiday lights'
I (867) EvLamp:     Mode: 0 (min 0, max 3, def 0)
I (873) EvLamp:     Speed: 8 (min 1, max 20, def 8)
I (878) EvLamp: Effect 15: 'Hoop'
I (882) EvLamp:     Speed: 15 (min 1, max 50, def 15)
I (888) EvLamp: Effect 16: 'Twister'
I (892) EvLamp:     Speed: 30 (min 0, max 40, def 30)
I (898) EvLamp:     Add black border: 1 (min 0, max 1, def 1)
I (904) EvLamp:     Iridescent colors: 0 (min 0, max 1, def 0)
I (911) EvLamp: Effect 17: 'Flower'
I (915) EvLamp:     Speed: 100 (min 1, max 255, def 100)
I (921) EvLamp:     Diameter: 128 (min 50, max 150, def 128)
I (927) EvLamp: Effect 18: 'Polar lights'
I (932) EvLamp:     Speed: 127 (min 1, max 255, def 127)
I (938) EvLamp:     Scale: 60 (min 1, max 255, def 60)
I (944) EvLamp:     Palette: 0 (min 0, max 1, def 0)
I (949) EvLamp:     Height adjustment: 50 (min 1, max 255, def 50)
I (956) EvLamp: Effect 19: 'Gif image'
I (961) EvLamp:     File: 0 (min 0, max 10, def 0)
I (966) EvLamp: Effect 20: 'Relax'
I (970) EvLamp:     Speed: 15 (min 1, max 100, def 15)
I (976) EvLamp:     Start hue: 100 (min 0, max 255, def 100)
I (982) EvLamp:     Saturation: 255 (min 0, max 255, def 255)
I (989) EvLamp:     Pixels to update: 1 (min 1, max 50, def 1)
I (995) EvLamp: Effect 21: 'Radiant wheel'
I (1000) EvLamp:     Rotation speed: 60 (min 0, max 255, def 60)
I (1007) EvLamp:     Hue 1: 0 (min 0, max 255, def 0)
I (1013) EvLamp:     Saturation 1: 255 (min 0, max 255, def 255)
I (1019) EvLamp:     Hue 2: 150 (min 0, max 255, def 150)
I (1025) EvLamp:     Saturation 2: 0 (min 0, max 255, def 0)
I (1032) EvLamp:     Number of rays: 3 (min 2, max 6, def 3)
I (1038) EvLamp: Effect 22: 'Peacock tail'
I (1043) EvLamp:     Speed: 200 (min 1, max 255, def 200)
I (1049) EvLamp:     Scale: 4 (min 1, max 10, def 4)
I (1055) EvLamp:     Saturation: 255 (min 0, max 255, def 255)
I (1061) EvLamp: Effect 23: 'Colors'
I (1065) EvLamp:     Speed: 192 (min 128, max 254, def 192)
I (1072) EvLamp:     Minimal saturation: 128 (min 1, max 255, def 128)
I (1079) EvLamp:     Maximal saturation: 255 (min 1, max 255, def 255)
I (1086) EvLamp: Effect 24: 'Diagonal movements'
I (1091) EvLamp:     Speed: 5 (min 1, max 10, def 5)
I (1097) EvLamp: Effect 25: 'Whirls'
I (1101) EvLamp:     Count: 20 (min 10, max 50, def 20)
I (1107) EvLamp:     Scale: 26 (min 5, max 50, def 26)
I (1113) EvLamp:     Palette: 0 (min 0, max 13, def 0)
I (1119) EvLamp:     Fadeout: 50 (min 10, max 250, def 50)
I (1125) EvLamp:     Time scale: 10 (min 1, max 10, def 10)
I (1131) EvLamp: Effect 26: 'Sun radiation'
I (1136) EvLamp:     Size: 8 (min 4, max 32, def 8)
I (1141) EvLamp:     Palette: 10 (min 0, max 13, def 10)
I (1147) EvLamp: Effect 27: 'Flight of spaceships'
I (1153) EvLamp:     Number of ships: 8 (min 2, max 16, def 8)
I (1159) EvLamp:     Direction change time: 5 (min 1, max 60, def 5)
I (1166) EvLamp: Effect 28: 'Fireflies'
I (1171) EvLamp:     Number of fireflies: 16 (min 4, max 48, def 16)
I (1178) EvLamp:     Chaotic movement: 1 (min 0, max 1, def 1)
I (1185) EvLamp:     Speed: 255 (min 1, max 255, def 255)
I (1191) EvLamp:     Update time: 3 (min 1, max 10, def 3)
I (1196) EvLamp: Effect 29: 'Tunnel'
I (1201) EvLamp:     Speed: 90 (min 1, max 170, def 90)
I (1207) EvLamp: Effect 30: 'Colored dunes'
I (1212) EvLamp:     Speed: 5 (min 1, max 40, def 5)
I (1217) EvLamp:     Palette: 1 (min 0, max 13, def 1)
I (1223) EvLamp: Effect 31: 'Octopus'
I (1228) EvLamp:     Speed: 3 (min 1, max 10, def 3)
I (1233) EvLamp:     Legs: 3 (min 2, max 10, def 3)
I (1238) EvLamp: Effect 32: 'Nuclear Noise'
I (1244) EvLamp:     Speed: 3 (min 1, max 10, def 3)
I (1249) EvLamp: Effect parameters loaded
I (1254) EvLamp: Maximal LED brightness: 255
I (1259) EvLamp: Surface configuration: 8x8 (64) LEDs, 1x1 (1) blocks
I (1266) EvLamp: Waiting for surface task to be ready...
I (1266) EvLamp: Block 0 LED strip config: 8x8, GPIO = 17, type = 0
I (1279) EvLamp: Surface ready
I (1283) EvLamp: Animation stopped
I (1288) EvLamp: Animation started
I (1291) EvLamp: Switched to effect 'Rainbow' (10)
I (1297) EvLamp: Starting WiFi in access point mode
I (1303) pp: pp rom version: e7ae62f
I (1306) net80211: net80211 rom version: e7ae62f
I (1313) wifi:wifi driver task: 3fcae2a0, prio:23, stack:6656, core=0
I (1337) wifi:wifi firmware version: 91b9630
I (1337) wifi:wifi certification version: v7.0
I (1337) wifi:config NVS flash: enabled
I (1338) wifi:config nano formating: disabled
I (1342) wifi:Init data frame dynamic rx buffer num: 32
I (1347) wifi:Init static rx mgmt buffer num: 5
I (1351) wifi:Init management short buffer num: 32
I (1355) wifi:Init dynamic tx buffer num: 32
I (1359) wifi:Init static tx FG buffer num: 2
I (1364) wifi:Init static rx buffer size: 1600
I (1368) wifi:Init static rx buffer num: 10
I (1372) wifi:Init dynamic rx buffer num: 32
I (1376) wifi_init: rx ba win: 6
I (1379) wifi_init: tcpip mbox: 32
I (1384) wifi_init: udp mbox: 6
I (1387) wifi_init: tcp mbox: 6
I (1391) wifi_init: tcp tx win: 5744
I (1395) wifi_init: tcp rx win: 5744
I (1400) wifi_init: tcp mss: 1440
I (1404) wifi_init: WiFi IRAM OP enabled
I (1408) wifi_init: WiFi RX IRAM OP enabled
I (1413) EvLamp: WiFi access point settings:
I (1418) EvLamp: --------------------------------------------------
I (1425) EvLamp: SSID: EvLamp
I (1429) EvLamp: Channel: 6
I (1432) EvLamp: Auth mode: Open
I (1436) EvLamp: --------------------------------------------------
I (1448) phy_init: phy_version 620,ec7ec30,Sep  5 2023,13:49:13
I (1489) wifi:mode : softAP (48:27:e2:36:7f:3d)
I (1490) wifi:Total power save buffer number: 16
I (1491) wifi:Init max length of beacon: 752/752
I (1492) wifi:Init max length of beacon: 752/752
I (1497) EvLamp: Unprocessed event 2
I (1498) esp_netif_lwip: DHCP server started on interface WIFI_AP_DEF with IP: 192.168.4.1
I (1499) main_task: Returned from app_main()
I (1509) EvLamp: WiFi started in access point mode
I (1521) EvLamp: --------------------------------------------------
I (1526) EvLamp: IP address: 192.168.1.1
I (1531) EvLamp: Netmask:    255.255.255.0
I (1536) EvLamp: Gateway:    192.168.1.1
I (1540) EvLamp: --------------------------------------------------
I (1547) EvLamp: DNS 0:      192.168.1.1
I (1552) EvLamp: DNS 1:      192.168.1.1
I (1556) EvLamp: DNS 2:      192.168.1.1
I (1561) EvLamp: --------------------------------------------------
I (1568) EvLamp: Network is up, restarting HTTPD...
I (1576) EvLamp: HTTPD started on port 80, free mem: 233220 bytes
I (2863) EvLamp: Animation paused
I (2863) EvLamp: Animation stopped
I (29156) wifi:new:<6,0>, old:<6,1>, ap:<6,1>, sta:<255,255>, prof:6
I (29157) wifi:station: a4:50:46:75:cf:31 join, AID=1, bgn, 20
I (29182) wifi:<ba-add>idx:2 (ifx:1, a4:50:46:75:cf:31), tid:0, ssn:0, winSize:64
I (29656) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.1.2
I (42933) EvLamp: Animation started
I (86428) wifi:station: a4:50:46:75:cf:31 leave, AID = 1, bss_flags is 33688691, bss:0x3fcbf86c
I (86429) wifi:new:<6,0>, old:<6,0>, ap:<6,1>, sta:<255,255>, prof:6
I (86432) wifi:<ba-del>idx:2, tid

**Comment by UncleRus** [comment]
Thank you. I see absolutely nothing abnormal in the logs. Do you have an oscilloscope or logic analyzer? And if there is, could you connect the device to the output GPIO and make sure that there is no signal there?

**Comment by Alfred1975** [comment]
I spend a lot of time trying to find a problem but the only solution after a lot of advices was to run `esptool flash_erase` and then flash your project.

After the full erase everything is seems working OK.

**Comment by UncleRus** [comment]
Great! I’m very glad that it worked out, albeit in such a strange way :)
